/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import ElementForm from './components/element-form'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElementForm: typeof ElementForm
  }
}
